#!/usr/bin/env bash
# BASH SCRIPT TO Install nginx web server

sudo apt-get update
sudo apt-get install nginx -y

# Nginx should be listening on port 80
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart
sudo service nginx reload
