#!/usr/bin/env bash
# BASH SCRIPT TO Install nginx web server

sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart
sudo service nginx reload
