#!/usr/bin/env bash
# BASH SCRIPT TO Install nginx web server
# AND
# Configure your Nginx server so that
# /redirect_me is redirecting to another page.

# Update package repository
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Allow HTTP traffic through UFW
sudo ufw allow 'Nginx HTTP'

# Create a directory to host the new page
sudo mkdir -p /var/www/html/redirect_me

# Create a simple HTML file for redirection
echo "This page has been moved permanently." | sudo tee /var/www/html/redirect_me/index.html

# Create a Nginx configuration file for the redirection
echo "server {
    listen 80;
    server_name localhost;

    location /redirect_me {
        return 301 /redirect_me/index.html;
    }
}" | sudo tee /etc/nginx/sites-available/redirect_me.conf

sudo rm -f /etc/nginx/sites-enabled/redirect_me.conf

# Create a symbolic link to enable the site configuration

sudo ln -s /etc/nginx/sites-available/redirect_me.conf /etc/nginx/sites-enabled/redirect_me.conf
# Test Nginx configuration
sudo nginx -t

# Restart Nginx to apply the changes
sudo systemctl restart nginx
