#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  "$USER":"$USER" /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 266856-web-01  54.89.60.84:80 check
    server 266856-web-02  54.85.95.79:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
