#!/usr/bin/env bash
#0. Nginx likes port 80
sudo apt-get update
sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'
sudo sed -i '/server_name localhost;/a listen 80;' /etc/nginx/sites-available/default

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default


fuser -k 80/tcp
sudo nginx -t
sudo systemctl restart nginx
service nginx restart
