#!/usr/bin/env bash
# Bash script that gives you information about the school file.
if [ ! -e ./school ]
then
echo "school file does not exist"
elif [ -f ./school ]
then
    echo "school file exists"
    if [ ! -s ./school ]
        then
        echo "school file is empty"
    elif [ -s ./school ]
        then
        echo "school file is not empty"
    elif [ ! -d ./school ]
    then
    echo "school is a regular file"
    fi
fi
