#!/usr/bin/env bash
# Bash script that gives you information about the school file.

if [ ! -e ./school ]
then
echo "school file does not exist"
else
    echo "school file exists"
    if [ ! -s ./school ]
        then
        echo "school file is empty"
	if [ ! -d ./school ]	
	then
	echo "school is a regular file"
	fi
    elif [ -s ./school ]
        then
        echo "school file is not empty"
        if [ ! -d ./school ]
        then
        echo "school is a regular file"
        fi
    fi
fi
