#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.

# Backup the original hosts file
cp /etc/hosts /etc/hosts.backup

#Define the new entries for localhost and facebook.com
localhost_entry="127.0.0.2       localhost"
facebook_entry="8.8.8.8         facebook.com"

#Remove any existing entries for localhost
#and 
#facebook.com from /etc/hosts
sed -i '/^127.0.0.1.*localhost/d' /etc/hosts
sed -i '/^::1.*localhost/d' /etc/hosts
sed -i '/^8.8.8.8.*facebook.com/d' /etc/hosts

# Add the new entries to /etc/hosts
echo "$localhost_entry" >> /etc/hosts
echo "$facebook_entry" >> /etc/hosts

