#!/usr/bin/env bash
#Bash script that displays all active IPv4 IPs on the machine it’s executed on
#ip -4 -o addr | awk "/(^\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}$)/ '{print $1}'"
ip -4 -o addr | awk '/inet/ {match($4, /([0-9]{1,3}\.){3}[0-9]{1,3}/); print substr($4, RSTART, RLENGTH)}'
