#!/usr/bin/env bash
# Bash script that accepts one argument
#the script should run the whoami command under the user passed as an argument
#nginx must be running as nginx user
#nginx must be listening on all active IPs on port 8080

user="nginx"


sudo -u "$user" nginx

#sudo nginx -t
#sudo systemctl restart nginx
